name = "tradevera-worker"
main = "src/index.ts"
compatibility_date = "2025-02-15"
workers_dev = true

[vars]
FRONTEND_ORIGIN = "https://tradevera-web.onrender.com"
APP_URL = "https://tradevera-web.onrender.com"
ALLOW_MAGIC_LINK_IN_RESPONSE = "true"

[[d1_databases]]
binding = "DB"
database_name = "tradevera"
database_id = "c1356677-73ba-49b8-9cc3-b385197d207b"
migrations_dir = "migrations"
